language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saravp123/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true saravp123/react-test npm run test

after_success:
  - docker build -t saravp123/multi-client ./client
  - docker build -t saravp123/multi-nginx ./nginx
  - docker build -t saravp123/multi-server ./server
  - docker build -t saravp123/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #- docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take those images and push them to docker hub
  - docker push saravp123/multi-client
  - docker push saravp123/multi-nginx
  - docker push saravp123/multi-server
  - docker push saravp123/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-508905327589
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY